name: UnstreamMenubar
options:
  bundleIdPrefix: lol.bgreen
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  SWIFT_VERSION: "5.9"
  MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  UnstreamMenubar:
    type: application
    platform: macOS
    sources:
      - UnstreamMenubar
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: lol.bgreen.UnstreamMenubar
      PRODUCT_NAME: Unstream
      INFOPLIST_FILE: UnstreamMenubar/Info.plist
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      ENABLE_HARDENED_RUNTIME: NO
      CODE_SIGN_ENTITLEMENTS: UnstreamMenubar/UnstreamMenubar.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: UnstreamMenubar/Info.plist
      properties:
        CFBundleName: Unstream
        CFBundleDisplayName: Unstream
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSUIElement: true
        NSHighResolutionCapable: true
        NSHumanReadableCopyright: "Copyright 2025 brandon lucas green"
        NSAppleEventsUsageDescription: "Unstream needs to check what music is playing so it can find the artist on ethical platforms."
