/**
 * Backfill artists.died_on from Wikidata.
 *
 * Usage:
 *   npx tsx scripts/backfill-artist-death-dates.ts            # dry run — prints what it would set
 *   npx tsx scripts/backfill-artist-death-dates.ts --apply
 *
 * Dry run is the default; --apply is the only thing that writes.
 *
 * The evidence rule is the whole point of this script. It resolves each artist to a Wikidata item
 * through the artist's own **MusicBrainz ID** (P434) and reads P570 (date of death) from that
 * item. It never matches on name, because name matching pairs "Sebastian Bach" with Johann
 * Sebastian Bach and "Jack White" with a footballer — both of which a name-based version of this
 * script actually did. A wrong death date would quietly delist a living artist from
 * /known-artists and from the weekly social posts, with nothing to signal it happened.
 *
 * MusicBrainz IDs come from data/artist-list.json, which is generated by
 * scripts/generate-artist-list.ts and holds the id alongside the name and slug. Artists absent
 * from that file get no verdict — NULL means "no death date recorded", never "alive", so
 * skipping them is the safe outcome rather than a gap to paper over.
 *
 * Re-runnable: it only writes rows whose stored died_on differs from what Wikidata says.
 */

import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';
import { readFileSync } from 'fs';
import { resolve } from 'path';

config({ path: resolve(import.meta.dirname ?? '.', '../.env') });

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_KEY;
if (!url || !key) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_KEY. Set them in .env or environment.');
  process.exit(1);
}
const client = createClient(url, key);
const apply = process.argv.includes('--apply');

const ENDPOINT = 'https://query.wikidata.org/sparql';
const UA = 'Unstream-DataAudit/1.0 (https://unstream.stream)';
const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));

/**
 * Wikidata throttles; a 429/503 is not an answer. Retrying rather than treating a throttled
 * request as "no death date" is the same rule as `shouldCache` in api/functions/cache.ts.
 */
async function sparql(query: string): Promise<Record<string, { value: string }>[]> {
  for (let attempt = 1; attempt <= 5; attempt++) {
    const res = await fetch(ENDPOINT, {
      method: 'POST',
      headers: {
        'User-Agent': UA,
        Accept: 'application/sparql-results+json',
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({ query }),
    });
    if (res.ok) return (await res.json()).results.bindings;
    if (res.status !== 429 && res.status !== 503) {
      throw new Error(`Wikidata HTTP ${res.status}: ${(await res.text()).slice(0, 200)}`);
    }
    await sleep(3000 * attempt);
  }
  throw new Error('Wikidata: still throttled after 5 attempts');
}

function chunk<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}

interface ArtistRow {
  id: string;
  slug: string;
  name: string;
  died_on: string | null;
}

async function main() {
  const listPath = resolve(import.meta.dirname ?? '.', '../data/artist-list.json');
  const list: { name: string; slug: string; musicbrainzId: string }[] = JSON.parse(
    readFileSync(listPath, 'utf8')
  );
  const mbidBySlug = new Map(list.map(a => [a.slug, a.musicbrainzId]));
  const mbidByName = new Map(list.map(a => [a.name.toLowerCase(), a.musicbrainzId]));

  // Read every stored artist, paging — PostgREST caps a response at 1,000 rows and truncates
  // silently, and this table is past that.
  const artists: ArtistRow[] = [];
  for (let from = 0; ; from += 1000) {
    const { data, error } = await client
      .from('artists')
      .select('id, slug, name, died_on')
      .order('slug')
      .range(from, from + 999);
    if (error) {
      console.error('Failed to read artists:', error.message);
      process.exit(1);
    }
    const batch = (data as ArtistRow[]) || [];
    artists.push(...batch);
    if (batch.length < 1000) break;
  }

  const resolvable = artists
    .map(a => ({ a, mbid: mbidBySlug.get(a.slug) || mbidByName.get(a.name.toLowerCase()) }))
    .filter((x): x is { a: ArtistRow; mbid: string } => !!x.mbid);

  console.log(
    `${artists.length} artist rows, ${resolvable.length} with a MusicBrainz id to resolve ` +
      `(${artists.length - resolvable.length} get no verdict)`
  );

  const deathByMbid = new Map<string, string>();
  for (const [i, group] of chunk(resolvable, 100).entries()) {
    const values = group.map(x => `"${x.mbid.replace(/"/g, '')}"`).join(' ');
    const rows = await sparql(`
SELECT ?mbid ?death WHERE {
  VALUES ?mbid { ${values} }
  ?item wdt:P434 ?mbid ;
        wdt:P31 wd:Q5 ;
        wdt:P570 ?death .
}`);
    for (const r of rows) deathByMbid.set(r.mbid.value, r.death.value.slice(0, 10));
    console.log(`  batch ${i + 1}/${chunk(resolvable, 100).length}: ${rows.length} with a death date`);
    await sleep(1500);
  }

  const changes = resolvable
    .map(({ a, mbid }) => ({ a, death: deathByMbid.get(mbid) || null }))
    .filter(({ a, death }) => death && a.died_on !== death);

  console.log(`\n${deathByMbid.size} deceased found, ${changes.length} row(s) to update\n`);
  for (const { a, death } of changes) {
    console.log(`  ${death}  ${a.slug.padEnd(30)} "${a.name}"`);
  }

  if (!apply) {
    console.log(`\nDry run. Re-run with --apply to write ${changes.length} date(s).`);
    return;
  }

  for (const { a, death } of changes) {
    const { error } = await client.from('artists').update({ died_on: death }).eq('id', a.id);
    if (error) {
      console.error(`Failed to set died_on for ${a.slug}: ${error.message}`);
      process.exitCode = 1;
    }
  }
  console.log(`\nWrote ${changes.length} date(s).`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
