// API endpoint: /api/saved-artists
// GET  — list user's saved artists with artist details
// POST — save an artist, remove a saved artist, bulk-check, or toggle supported
//   Action is determined by the `action` field in the POST body:
//   action: "save"      (default) — save an artist
//   action: "remove"              — remove a saved artist
//   action: "check"               — bulk check which artists are saved
//   action: "support"             — mark a saved artist as supported
//   action: "unsupport"           — unmark a saved artist as supported
//
// Saving an artist does NOT create a row in the `artists` table.
// Unclaimed artists don't get /a/ profile pages — only claimed ones do.
// We store the search result data (slug, name, imageUrl) directly in saved_artists.

import { getClient } from './db';
import { checkRateLimit, accountRateLimitKey, checkSentryDedup, getClientIp } from './ratelimit';
import { authenticateBearerFast } from './middleware';
import { requestArtistCatalog } from './request-catalog';
import { Sentry } from '../lib/sentry';

function getServiceClient() {
  return getClient();
}

/**
 * Report a save/remove this endpoint refused or couldn't complete.
 *
 * Nothing else sees these. `console.error` in a Lambda is written to a log nobody reads, the
 * browser extension fires its save and never looks at the response, and the web app only rolls
 * its optimistic update back — so a fan watching the heart fill in and empty again was the entire
 * observability story. Two bugs lived behind that: the React artist page sent the artists-table
 * UUID where a slug belongs, and the slug format check rejected 24 of the published artist slugs.
 * Both answered 400 on every attempt, for weeks, in silence.
 *
 * Deduped on `reason` alone with a short window rather than on the offending value: `reason` is a
 * fixed set, so a client looping on a rejection can't flood the project by varying the slug it
 * sends. The first event in each window carries the value, which is all that's needed to diagnose.
 * No user id in the key — dedup keys shouldn't hold PII.
 */
async function reportSavedArtistFailure(
  reason: string,
  message: string,
  detail: Record<string, unknown> = {},
): Promise<void> {
  if (!await checkSentryDedup(`saved-artists:${reason}`, 300)) return;
  Sentry.captureMessage(`[saved-artists] ${message}`, {
    level: 'error',
    tags: { reason },
    extra: { context: `saved-artists.${reason}`, ...detail },
  });
}

/**
 * The identifier every client sends as `artistId` is an artist **slug**, never a database id.
 * Returns an error message when it isn't one, or null when it's fine.
 *
 * Shared by save and remove so the two can't disagree about what they accept. Remove used to
 * accept anything, which is why unsaving with a UUID matched no rows and still answered 200 —
 * a success that had done nothing.
 */
function invalidArtistSlugReason(artistSlug: string): { reason: string; error: string } | null {
  // Defense in depth: reject slugs that don't match the canonical artist slug format. This
  // prevents stored XSS via malicious slugs reaching the edge function SSR — the character class
  // is what does that work, by admitting nothing that can break out of HTML.
  //
  // The bound used to be 3–20 characters, copied from migration 021's `username_format`. That
  // constraint is about *usernames*, which people choose; artist slugs are generated by slugify()
  // from an artist's name and are neither that short nor that bounded. It rejected 24 of the 791
  // published artist slugs — 'explosions-in-the-sky', 'queens-of-the-stone-age', 'bt', 'iq', 'x'
  // — so saving those artists 400'd. 60 is comfortably above the longest one we publish (38).
  const SLUG_REGEX = /^[a-z0-9](?:[a-z0-9-]{0,58}[a-z0-9])?$/;
  if (!SLUG_REGEX.test(artistSlug)) {
    return { reason: 'invalid-slug-format', error: 'Invalid artist slug format' };
  }

  // A lowercase UUID is all hyphens and hex, so it satisfies the slug format above — the old
  // 20-character cap was the only thing rejecting one. Say so rather than accepting it: nothing
  // matches in the artists table, so the row would be stored under the UUID with a name titleized
  // from it, and the /u/:handle page would then link a /a/{uuid} URL that 404s. Every write has
  // always gone through the format check above, so no such row can already exist to be removed.
  const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
  if (UUID_REGEX.test(artistSlug)) {
    return { reason: 'uuid-not-slug', error: 'artistId must be an artist slug, not an id' };
  }

  return null;
}

/** Truncated so an arbitrary client value can't blow up a Sentry tag. */
function forTag(value: string): string {
  return value.length > 64 ? `${value.slice(0, 64)}…` : value;
}

// Fire-and-forget CDN cache purge by tag. Same pattern as artist-profile.ts.
// No-op (with warning) if env vars aren't set (local dev/tests).
function purgeCacheTag(handle: string): void {
  const siteId = process.env.NETLIFY_SITE_ID || process.env.SITE_ID;
  const token = process.env.NETLIFY_API_TOKEN;
  if (!siteId || !token) {
    console.warn(`[saved-artists] NETLIFY_SITE_ID or NETLIFY_API_TOKEN not set, skipping CDN purge for user-share-${handle}`);
    return;
  }
  fetch('https://api.netlify.com/api/v1/purge', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      site_id: siteId,
      cache_tags: [`user-share-${handle}`],
    }),
  })
    .then(() => console.log(`[saved-artists] Purged CDN cache for user-share-${handle}`))
    .catch((e) => console.error(`[saved-artists] CDN cache purge failed for user-share-${handle}:`, e));
}

const CORS_HEADERS = {
  'Content-Type': 'application/json',
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
};

export async function handler(event: {
  httpMethod: string;
  headers: Record<string, string | undefined>;
  body: string | null;
}) {
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, headers: CORS_HEADERS, body: '' };
  }

  // Rate-limit check (Redis) and token validation (Supabase Auth) are both
  // network round-trips with no data dependency — run them concurrently. Deriving
  // the rate-limit key first costs nothing to that: it verifies the JWT locally.
  const ip = getClientIp(event.headers);
  const rlKey = await accountRateLimitKey(event.headers.authorization, ip);
  const rlPromise = checkRateLimit(rlKey, 'account', CORS_HEADERS);
  const userPromise = authenticateBearerFast(event.headers.authorization).catch(() => null);
  const rl = await rlPromise;
  if (rl.limited) return rl.response;

  const client = getServiceClient();
  if (!client) {
    // Every save, remove and list fails while this is true, so it needs to be loud rather than a
    // 500 that reads like an intermittent glitch.
    await reportSavedArtistFailure('db-not-configured', 'Supabase is not configured — no saved-artist request can succeed', {
      httpMethod: event.httpMethod,
    });
    return { statusCode: 500, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Database not configured' }) };
  }

  // GET: List user's saved artists (auth required)
  if (event.httpMethod === 'GET') {
    const user = await userPromise;
    if (!user) {
      return { statusCode: 401, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Not authenticated' }) };
    }

    try {
      const { data: saved, error: savedError } = await client
        .from('saved_artists')
        .select(`
          id,
          user_id,
          artist_id,
          artist_slug,
          artist_name,
          artist_image_url,
          notes,
          added_at,
          supported,
          supported_at,
          last_modified,
          device_id,
          artists!left (id, name, slug, image_url)
        `)
        .eq('user_id', user.userId)
        .eq('deleted', false);

      if (savedError) {
        console.error('[saved-artists] Error fetching saved artists:', savedError);
        await reportSavedArtistFailure('list-query-failed', 'Listing saved artists failed at the database', {
          dbMessage: savedError.message,
          dbCode: savedError.code,
        });
        return { statusCode: 500, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Failed to fetch saved artists' }) };
      }

      const savedArtists = (saved || []).map(row => {
        // Prefer data from the artists table (claimed/verified artists) when available
        const artistRow = (row as any).artists;
        const claimed = !!artistRow;
        return {
          artistId: artistRow?.slug || row.artist_slug || row.artist_id,
          name: artistRow?.name || row.artist_name || 'Unknown',
          slug: artistRow?.slug || row.artist_slug || '',
          imageUrl: artistRow?.image_url || row.artist_image_url || null,
          notes: row.notes,
          addedAt: row.added_at,
          supported: row.supported,
          supportedAt: row.supported_at,
          lastModified: row.last_modified,
          deviceId: row.device_id,
          claimed,
        };
      });

      return {
        statusCode: 200,
        headers: CORS_HEADERS,
        body: JSON.stringify({ savedArtists }),
      };
    } catch (error) {
      console.error('[saved-artists] GET error:', error);
      Sentry.captureException(error, { tags: { reason: 'list-threw' }, extra: { context: 'saved-artists.list' } });
      return { statusCode: 500, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Internal server error' }) };
    }
  }

  // POST: Route by action field
  if (event.httpMethod === 'POST') {
    const user = await userPromise;
    if (!user) {
      return { statusCode: 401, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Not authenticated' }) };
    }

    let body: Record<string, unknown>;
    try {
      body = JSON.parse(event.body || '{}');
    } catch {
      return { statusCode: 400, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Invalid JSON' }) };
    }

    const action = (body.action as string) || 'save';

    if (action === 'check') {
      return handleCheck(user, body, client);
    }
    if (action === 'remove') {
      return handleRemove(user, body, client);
    }
    if (action === 'support') {
      return handleSupport(user, body, client);
    }
    if (action === 'unsupport') {
      return handleUnsupport(user, body, client);
    }
    return handleSave(user, body, client);
  }

  return { statusCode: 404, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Not found' }) };
}

// Resolve a slug to an existing artists table row (no creation).
// Only claimed/verified artists will have rows.
async function findExistingArtist(
  client: ReturnType<typeof getServiceClient>,
  slug: string,
): Promise<{ id: string; name: string; slug: string; image_url: string | null } | null> {
  // Exact and case-insensitive lookups run in parallel; exact match wins.
  const [{ data: exact }, { data: ciData }] = await Promise.all([
    client
      .from('artists')
      .select('id, name, slug, image_url')
      .eq('slug', slug)
      .single(),
    client
      .from('artists')
      .select('id, name, slug, image_url')
      .ilike('slug', slug)
      .single(),
  ]);
  return exact || ciData;
}

async function handleSave(user: { userId: string; email: string }, body: Record<string, unknown>, client: ReturnType<typeof getServiceClient>) {
  const artistSlug = (body.artistId as string) || (body.slug as string);
  const artistName = body.name as string | undefined;
  const artistImageUrl = body.imageUrl as string | undefined;

  if (!artistSlug) {
    await reportSavedArtistFailure('save-missing-artist-id', 'Save rejected — no artistId in the body', {
      bodyKeys: Object.keys(body),
    });
    return { statusCode: 400, headers: CORS_HEADERS, body: JSON.stringify({ error: 'artistId (slug) is required' }) };
  }

  const invalid = invalidArtistSlugReason(artistSlug);
  if (invalid) {
    await reportSavedArtistFailure(`save-${invalid.reason}`, `Save rejected — ${invalid.error}`, {
      artistSlug: forTag(artistSlug),
      artistSlugLength: artistSlug.length,
      artistName,
    });
    return { statusCode: 400, headers: CORS_HEADERS, body: JSON.stringify({ error: invalid.error }) };
  }

  try {
    // Check if this artist already has a row in the artists table (claimed/verified)
    const existingArtist = await findExistingArtist(client, artistSlug);
    const artistId = existingArtist?.id || null;
    const name = existingArtist?.name || artistName || artistSlug.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    const imageUrl = existingArtist?.image_url || artistImageUrl || null;
    const slug = existingArtist?.slug || artistSlug;

    // Upsert — idempotent if already saved
    // UNS-93: accept optional device_id for sync.
    // UNS-112: stamp last_modified server-side as the authoritative timestamp
    // so clock skew between client and server doesn't hide saves from incremental pulls.
    // The DB trigger overwrites last_modified on UPDATE, but setting it on INSERT
    // ensures the row is immediately visible to ?since= queries using server time.
    const serverNow = new Date().toISOString();
    const upsertPayload: Record<string, unknown> = {
      user_id: user.userId,
      artist_id: artistId,
      artist_slug: slug,
      artist_name: name,
      artist_image_url: imageUrl,
      notes: (body.notes as string) || null,
      last_modified: serverNow,
      // Clear tombstone if re-saving a previously-removed artist
      deleted: false,
      deleted_at: null,
    };
    if (body.device_id !== undefined) {
      if (typeof body.device_id === 'string') {
        upsertPayload.device_id = body.device_id.slice(0, 128);
      }
    }

    const { data: saved, error: upsertError } = await client
      .from('saved_artists')
      .upsert(upsertPayload, { onConflict: 'user_id,artist_slug' })
      .select()
      .single();

    if (upsertError) {
      console.error('[saved-artists] Error saving artist:', upsertError);
      await reportSavedArtistFailure('save-upsert-failed', 'Saving an artist failed at the database', {
        artistSlug: forTag(slug),
        dbMessage: upsertError.message,
        dbCode: upsertError.code,
      });
      return { statusCode: 500, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Failed to save artist' }) };
    }

    // Saving is the strongest signal that someone wants this artist's releases — it's what
    // feeds their release alerts and, later, their calendar. Catalog on the way through.
    // 'saved' outranks 'searched' when the hourly cap is reached, so a deliberate save still
    // gets through while opportunistic search-triggered crawls are dropped.
    if (artistId) {
      await requestArtistCatalog([artistId], 'saved');
    }

    return {
      statusCode: 200,
      headers: CORS_HEADERS,
      body: JSON.stringify({
        success: true,
        server_time: serverNow,
        savedArtist: {
          artistId: slug,
          name,
          slug,
          imageUrl,
          notes: saved.notes,
          addedAt: saved.added_at,
          lastModified: saved.last_modified,
          deviceId: saved.device_id,
        },
      }),
    };
  } catch (error) {
    console.error('[saved-artists] Save error:', error);
    Sentry.captureException(error, { tags: { reason: 'save-threw' }, extra: { context: 'saved-artists.save' } });
    return { statusCode: 500, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Internal server error' }) };
  }
}

async function handleRemove(user: { userId: string; email: string }, body: Record<string, unknown>, client: ReturnType<typeof getServiceClient>) {
  const artistSlug = (body.artistId as string) || (body.slug as string);
  if (!artistSlug) {
    await reportSavedArtistFailure('remove-missing-artist-id', 'Remove rejected — no artistId in the body', {
      bodyKeys: Object.keys(body),
    });
    return { statusCode: 400, headers: CORS_HEADERS, body: JSON.stringify({ error: 'artistId is required' }) };
  }

  // Remove validates the identifier the same way save does. It used to accept anything, so
  // unsaving with a UUID matched no rows and still answered 200 — a success that had done nothing.
  const invalid = invalidArtistSlugReason(artistSlug);
  if (invalid) {
    await reportSavedArtistFailure(`remove-${invalid.reason}`, `Remove rejected — ${invalid.error}`, {
      artistSlug: forTag(artistSlug),
      artistSlugLength: artistSlug.length,
    });
    return { statusCode: 400, headers: CORS_HEADERS, body: JSON.stringify({ error: invalid.error }) };
  }

  try {
    // UNS-112: soft-delete (tombstone) instead of hard DELETE so
    // incremental pulls (?since=) can propagate removals to other devices.
    // The sharing lookup (read-only) runs concurrently with the tombstone write;
    // the CDN purge itself only fires once the write has succeeded.
    const removeTime = new Date().toISOString();
    const [{ error: updateError }, unameResult] = await Promise.all([
      client
        .from('saved_artists')
        .update({ deleted: true, deleted_at: removeTime, last_modified: removeTime })
        .eq('user_id', user.userId)
        .eq('artist_slug', artistSlug)
        .eq('deleted', false),
      client
        .from('usernames')
        .select('username, saved_artists_public')
        .eq('user_id', user.userId)
        .maybeSingle()
        .then(res => res, (e: unknown) => {
          console.error('[saved-artists] CDN purge lookup failed:', e);
          return { data: null };
        }),
    ]);

    if (updateError) {
      console.error('[saved-artists] Error removing saved artist:', updateError);
      await reportSavedArtistFailure('remove-update-failed', 'Removing a saved artist failed at the database', {
        artistSlug: forTag(artistSlug),
        dbMessage: updateError.message,
        dbCode: updateError.code,
      });
      return { statusCode: 500, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Failed to remove saved artist' }) };
    }

    // If the user has public sharing enabled, purge the CDN cache for their page
    // so the removed artist disappears immediately instead of serving stale for ~5 min.
    const uname = unameResult.data;
    if (uname?.saved_artists_public && uname.username) {
      purgeCacheTag(uname.username);
    }

    return {
      statusCode: 200,
      headers: CORS_HEADERS,
      body: JSON.stringify({ success: true, server_time: removeTime }),
    };
  } catch (error) {
    console.error('[saved-artists] Remove error:', error);
    Sentry.captureException(error, { tags: { reason: 'remove-threw' }, extra: { context: 'saved-artists.remove' } });
    return { statusCode: 500, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Internal server error' }) };
  }
}

async function handleCheck(user: { userId: string; email: string }, body: Record<string, unknown>, client: ReturnType<typeof getServiceClient>) {
  const artistSlugs = body.artistIds as string[];
  if (!artistSlugs || !Array.isArray(artistSlugs)) {
    return { statusCode: 400, headers: CORS_HEADERS, body: JSON.stringify({ error: 'artistIds array is required' }) };
  }

  // Cap at 100 IDs
  if (artistSlugs.length > 100) {
    return { statusCode: 400, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Maximum 100 artist IDs allowed' }) };
  }

  try {
    // Look up saved artists by slug (the identifier the frontend uses)
    const { data: saved, error: checkError } = await client
      .from('saved_artists')
      .select('artist_slug')
      .eq('user_id', user.userId)
      .eq('deleted', false)
      .in('artist_slug', artistSlugs);

    if (checkError) {
      console.error('[saved-artists] Error checking saved artists:', checkError);
      await reportSavedArtistFailure('check-query-failed', 'Bulk-checking saved artists failed at the database', {
        dbMessage: checkError.message,
        dbCode: checkError.code,
      });
      return { statusCode: 500, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Failed to check saved artists' }) };
    }

    const savedArtistIds = (saved || []).map((row: any) => row.artist_slug);

    return {
      statusCode: 200,
      headers: CORS_HEADERS,
      body: JSON.stringify({ savedArtistIds }),
    };
  } catch (error) {
    console.error('[saved-artists] Check error:', error);
    Sentry.captureException(error, { tags: { reason: 'check-threw' }, extra: { context: 'saved-artists.check' } });
    return { statusCode: 500, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Internal server error' }) };
  }
}

async function handleSupport(user: { userId: string; email: string }, body: Record<string, unknown>, client: ReturnType<typeof getServiceClient>) {
  const artistSlug = (body.artistId as string) || (body.slug as string);
  if (!artistSlug) {
    return { statusCode: 400, headers: CORS_HEADERS, body: JSON.stringify({ error: 'artistId is required' }) };
  }

  try {
    // Idempotent: set supported=true even if already true
    const { data: updated, error: updateError } = await client
      .from('saved_artists')
      .update({ supported: true, supported_at: new Date().toISOString() })
      .eq('user_id', user.userId)
      .eq('artist_slug', artistSlug)
      .eq('deleted', false)
      .select(`
        id, user_id, artist_id, artist_slug, artist_name, artist_image_url,
        notes, added_at, supported, supported_at, last_modified, device_id,
        artists!left (id, name, slug, image_url)
      `)
      .single();

    if (updateError) {
      console.error('[saved-artists] Error supporting artist:', updateError);
      await reportSavedArtistFailure('support-update-failed', 'Marking an artist as supported failed at the database', {
        artistSlug: forTag(artistSlug),
        dbMessage: updateError.message,
        dbCode: updateError.code,
      });
      return { statusCode: 500, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Failed to support artist' }) };
    }

    if (!updated) {
      return { statusCode: 404, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Saved artist not found' }) };
    }

    const artistRow = (updated as any).artists;
    const claimed = !!artistRow;

    return {
      statusCode: 200,
      headers: CORS_HEADERS,
      body: JSON.stringify({
        success: true,
        savedArtist: {
          artistId: artistRow?.slug || updated.artist_slug || updated.artist_id,
          name: artistRow?.name || updated.artist_name || 'Unknown',
          slug: artistRow?.slug || updated.artist_slug || '',
          imageUrl: artistRow?.image_url || updated.artist_image_url || null,
          notes: updated.notes,
          addedAt: updated.added_at,
          supported: updated.supported,
          supportedAt: updated.supported_at,
          lastModified: updated.last_modified,
          deviceId: updated.device_id,
          claimed,
        },
      }),
    };
  } catch (error) {
    console.error('[saved-artists] Support error:', error);
    Sentry.captureException(error, { tags: { reason: 'support-threw' }, extra: { context: 'saved-artists.support' } });
    return { statusCode: 500, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Internal server error' }) };
  }
}

async function handleUnsupport(user: { userId: string; email: string }, body: Record<string, unknown>, client: ReturnType<typeof getServiceClient>) {
  const artistSlug = (body.artistId as string) || (body.slug as string);
  if (!artistSlug) {
    return { statusCode: 400, headers: CORS_HEADERS, body: JSON.stringify({ error: 'artistId is required' }) };
  }

  try {
    // Idempotent: set supported=false even if already false
    const { data: updated, error: updateError } = await client
      .from('saved_artists')
      .update({ supported: false, supported_at: null })
      .eq('user_id', user.userId)
      .eq('artist_slug', artistSlug)
      .eq('deleted', false)
      .select(`
        id, user_id, artist_id, artist_slug, artist_name, artist_image_url,
        notes, added_at, supported, supported_at, last_modified, device_id,
        artists!left (id, name, slug, image_url)
      `)
      .single();

    if (updateError) {
      console.error('[saved-artists] Error unsupporting artist:', updateError);
      await reportSavedArtistFailure('unsupport-update-failed', 'Unmarking an artist as supported failed at the database', {
        artistSlug: forTag(artistSlug),
        dbMessage: updateError.message,
        dbCode: updateError.code,
      });
      return { statusCode: 500, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Failed to unsupport artist' }) };
    }

    if (!updated) {
      return { statusCode: 404, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Saved artist not found' }) };
    }

    const artistRow = (updated as any).artists;
    const claimed = !!artistRow;

    return {
      statusCode: 200,
      headers: CORS_HEADERS,
      body: JSON.stringify({
        success: true,
        savedArtist: {
          artistId: artistRow?.slug || updated.artist_slug || updated.artist_id,
          name: artistRow?.name || updated.artist_name || 'Unknown',
          slug: artistRow?.slug || updated.artist_slug || '',
          imageUrl: artistRow?.image_url || updated.artist_image_url || null,
          notes: updated.notes,
          addedAt: updated.added_at,
          supported: updated.supported,
          supportedAt: updated.supported_at,
          lastModified: updated.last_modified,
          deviceId: updated.device_id,
          claimed,
        },
      }),
    };
  } catch (error) {
    console.error('[saved-artists] Unsupport error:', error);
    Sentry.captureException(error, { tags: { reason: 'unsupport-threw' }, extra: { context: 'saved-artists.unsupport' } });
    return { statusCode: 500, headers: CORS_HEADERS, body: JSON.stringify({ error: 'Internal server error' }) };
  }
}
